name: sample-factory-pytorch1.4
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2019.11.28=hecc5488_0
  - cairo=1.16.0=hfb77d84_1002
  - certifi=2019.11.28=py37hc8dfbb8_1
  - cudatoolkit=10.1.243=h6bb024c_0
  - dbus=1.13.6=he372182_0
  - expat=2.2.9=he1b5a44_2
  - ffmpeg=4.1.3=h167e202_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.9.1=h8a8886c_1
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.2.1=h516909a_2
  - glib=2.58.3=py37he00f558_1003
  - gmp=6.2.0=he1b5a44_2
  - gnutls=3.6.5=hd3a4fd2_1002
  - graphite2=1.3.13=hf484d3e_1000
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - icu=64.2=he1b5a44_1
  - intel-openmp=2020.0=166
  - jasper=1.900.1=h07fcdf6_1006
  - jpeg=9c=h14c3975_1001
  - lame=3.100=h14c3975_1001
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=15_mkl
  - libcblas=3.8.0=15_mkl
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=15_mkl
  - liblapacke=3.8.0=15_mkl
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.0.2=h56121f0_5
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=hee79883_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.2=he6710b0_0
  - nettle=3.4.1=h1bed415_1002
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - olefile=0.46=py37_0
  - opencv=4.1.0=py37h3aa1047_6
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1d=h516909a_0
  - pcre=8.44=he1b5a44_0
  - pillow=7.0.0=py37hb39fc2d_0
  - pip=20.0.2=py37_1
  - pixman=0.38.0=h516909a_1003
  - pthread-stubs=0.4=h14c3975_1001
  - python=3.7.6=h0371630_2
  - python_abi=3.7=1_cp37m
  - pytorch=1.4.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - qt=5.9.7=h0c104cb_3
  - readline=7.0=h7b6447c_5
  - setuptools=46.0.0=py37_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.5.0=py37_cu101
  - wheel=0.34.2=py37_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - atari-py==0.2.6
    - cloudpickle==1.3.0
    - colorlog==4.1.0
    - cython==0.29.15
    - faster-fifo==1.0.7
    - filelock==3.0.12
    - future==0.18.2
    - gast==0.2.2
    - google-pasta==0.2.0
    - gputil==1.4.0
    - grpcio==1.27.2
    - gym==0.17.1
    - h5py==2.10.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - lockfile==0.12.2
    - lz4==3.0.2
    - markdown==3.2.1
    - opt-einsum==3.2.0
    - pandas==1.0.1
    - protobuf==3.11.3
    - psutil==5.7.0
    - pyglet==1.5.0
    - python-dateutil==2.8.1
    - pytz==2019.3
    - scipy==1.4.1
    - tensorboard==1.15.0
    - tensorboardx==2.0
    - termcolor==1.1.0
    - werkzeug==1.0.0
    - wrapt==1.12.1
    - threadpoolctl==2.0.0

